services:
  postgres:
    image: postgres:16-alpine
    container_name: battlequest_postgres
    environment:
      POSTGRES_DB: battlequest
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - battlequest_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d battlequest"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  battlequest_pgdata:
