// <auto-generated />
using System;
using BattleQuest.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BattleQuest.Infrastructure.Migrations
{
    [DbContext(typeof(BattleQuestDbContext))]
    partial class BattleQuestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BattleQuest.Domain.Entities.ActionType", b =>
                {
                    b.Property<int>("ActionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("action_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActionTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("ActionTypeId")
                        .HasName("pk_action_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_action_types_name");

                    b.ToTable("action_types", (string)null);
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Boss", b =>
                {
                    b.Property<int>("BossId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("boss_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BossId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("BossId")
                        .HasName("pk_bosses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_bosses_name");

                    b.ToTable("bosses", (string)null);
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChannelId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("ChannelId")
                        .HasName("pk_channels");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_name");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("action_type_id");

                    b.Property<int?>("BossId")
                        .HasColumnType("integer")
                        .HasColumnName("boss_id");

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    b.Property<int?>("Damage")
                        .HasColumnType("integer")
                        .HasColumnName("damage");

                    b.Property<string>("EventHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("event_hash");

                    b.Property<int?>("Gold")
                        .HasColumnType("integer")
                        .HasColumnName("gold");

                    b.Property<int?>("Hp")
                        .HasColumnType("integer")
                        .HasColumnName("hp");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("inserted_at");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("KillerPlayerId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("killer_player_id");

                    b.Property<int?>("LocationX")
                        .HasColumnType("integer")
                        .HasColumnName("location_x");

                    b.Property<int?>("LocationY")
                        .HasColumnType("integer")
                        .HasColumnName("location_y");

                    b.Property<string>("MessageText")
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("Method")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PlayerId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("player_id");

                    b.Property<int?>("PlayerLevel")
                        .HasColumnType("integer")
                        .HasColumnName("player_level");

                    b.Property<int?>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("QuestId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("quest_id");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw");

                    b.Property<string>("Reason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reason");

                    b.Property<string>("VictimPlayerId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("victim_player_id");

                    b.Property<int?>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("EventId")
                        .HasName("pk_events");

                    b.HasIndex("BossId")
                        .HasDatabaseName("ix_events_boss_id");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_events_channel_id");

                    b.HasIndex("EventHash")
                        .IsUnique()
                        .HasDatabaseName("ix_events_event_hash");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_events_item_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_events_occurred_at");

                    b.HasIndex("QuestId")
                        .HasDatabaseName("ix_events_quest_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_events_zone_id");

                    b.HasIndex("ActionTypeId", "ItemId")
                        .HasDatabaseName("ix_events_action_type_id_item_id");

                    b.HasIndex("KillerPlayerId", "ActionTypeId")
                        .HasDatabaseName("ix_events_killer_player_id_action_type_id");

                    b.HasIndex("PlayerId", "ActionTypeId")
                        .HasDatabaseName("ix_events_player_id_action_type_id");

                    b.HasIndex("VictimPlayerId", "ActionTypeId")
                        .HasDatabaseName("ix_events_victim_player_id_action_type_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ItemId")
                        .HasName("pk_items");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_items_name");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("player_id");

                    b.Property<int?>("LastKnownLevel")
                        .HasColumnType("integer")
                        .HasColumnName("last_known_level");

                    b.Property<int?>("LastKnownZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("last_known_zone_id");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("PlayerId")
                        .HasName("pk_players");

                    b.HasIndex("LastKnownZoneId")
                        .HasDatabaseName("ix_players_last_known_zone_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_players_name");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Quest", b =>
                {
                    b.Property<string>("QuestId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("quest_id");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("QuestId")
                        .HasName("pk_quests");

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZoneId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ZoneId")
                        .HasName("pk_zones");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_zones_name");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Event", b =>
                {
                    b.HasOne("BattleQuest.Domain.Entities.ActionType", "ActionType")
                        .WithMany("Events")
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_action_types_action_type_id");

                    b.HasOne("BattleQuest.Domain.Entities.Boss", "Boss")
                        .WithMany("Events")
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_bosses_boss_id");

                    b.HasOne("BattleQuest.Domain.Entities.Channel", "Channel")
                        .WithMany("Events")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_channels_channel_id");

                    b.HasOne("BattleQuest.Domain.Entities.Item", "Item")
                        .WithMany("Events")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_items_item_id");

                    b.HasOne("BattleQuest.Domain.Entities.Player", "KillerPlayer")
                        .WithMany()
                        .HasForeignKey("KillerPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_players_killer_player_id");

                    b.HasOne("BattleQuest.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_players_player_id");

                    b.HasOne("BattleQuest.Domain.Entities.Quest", "Quest")
                        .WithMany("Events")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_quests_quest_id");

                    b.HasOne("BattleQuest.Domain.Entities.Player", "VictimPlayer")
                        .WithMany()
                        .HasForeignKey("VictimPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_players_victim_player_id");

                    b.HasOne("BattleQuest.Domain.Entities.Zone", "Zone")
                        .WithMany("Events")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_zones_zone_id");

                    b.Navigation("ActionType");

                    b.Navigation("Boss");

                    b.Navigation("Channel");

                    b.Navigation("Item");

                    b.Navigation("KillerPlayer");

                    b.Navigation("Player");

                    b.Navigation("Quest");

                    b.Navigation("VictimPlayer");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Player", b =>
                {
                    b.HasOne("BattleQuest.Domain.Entities.Zone", "LastKnownZone")
                        .WithMany("LastKnownPlayers")
                        .HasForeignKey("LastKnownZoneId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_players_zones_last_known_zone_id");

                    b.Navigation("LastKnownZone");
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.ActionType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Boss", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Channel", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Item", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Quest", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BattleQuest.Domain.Entities.Zone", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("LastKnownPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
