CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

CREATE TABLE action_types (
    action_type_id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    CONSTRAINT pk_action_types PRIMARY KEY (action_type_id)
);

CREATE TABLE bosses (
    boss_id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    CONSTRAINT pk_bosses PRIMARY KEY (boss_id)
);

CREATE TABLE channels (
    channel_id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) NOT NULL,
    CONSTRAINT pk_channels PRIMARY KEY (channel_id)
);

CREATE TABLE items (
    item_id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (item_id)
);

CREATE TABLE quests (
    quest_id varchar(20) NOT NULL,
    name varchar(100),
    CONSTRAINT pk_quests PRIMARY KEY (quest_id)
);

CREATE TABLE zones (
    zone_id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    CONSTRAINT pk_zones PRIMARY KEY (zone_id)
);

CREATE TABLE players (
    player_id varchar(20) NOT NULL,
    last_known_zone_id integer,
    name varchar(100),
    last_known_level integer,
    CONSTRAINT pk_players PRIMARY KEY (player_id),
    CONSTRAINT fk_players_zones_last_known_zone_id FOREIGN KEY (last_known_zone_id) REFERENCES zones (zone_id) ON DELETE SET NULL
);

CREATE TABLE events (
    event_id integer GENERATED BY DEFAULT AS IDENTITY,
    channel_id integer NOT NULL,
    action_type_id integer NOT NULL,
    player_id varchar(20),
    victim_player_id varchar(20),
    killer_player_id varchar(20),
    quest_id varchar(20),
    zone_id integer,
    item_id integer,
    boss_id integer,
    occurred_at timestamptz NOT NULL,
    quantity integer,
    xp integer,
    gold integer,
    hp integer,
    damage integer,
    method varchar(100),
    player_level integer,
    points integer,
    reason varchar(255),
    location_x integer,
    location_y integer,
    message_text text,
    inserted_at timestamptz NOT NULL,
    raw text NOT NULL,
    event_hash varchar(64) NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (event_id),
    CONSTRAINT fk_events_action_types_action_type_id FOREIGN KEY (action_type_id) REFERENCES action_types (action_type_id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_bosses_boss_id FOREIGN KEY (boss_id) REFERENCES bosses (boss_id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_channels_channel_id FOREIGN KEY (channel_id) REFERENCES channels (channel_id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_items_item_id FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_players_killer_player_id FOREIGN KEY (killer_player_id) REFERENCES players (player_id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_players_player_id FOREIGN KEY (player_id) REFERENCES players (player_id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_players_victim_player_id FOREIGN KEY (victim_player_id) REFERENCES players (player_id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_quests_quest_id FOREIGN KEY (quest_id) REFERENCES quests (quest_id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_zones_zone_id FOREIGN KEY (zone_id) REFERENCES zones (zone_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX ix_action_types_name ON action_types (name);

CREATE UNIQUE INDEX ix_bosses_name ON bosses (name);

CREATE UNIQUE INDEX ix_channels_name ON channels (name);

CREATE INDEX ix_events_action_type_id_item_id ON events (action_type_id, item_id);

CREATE INDEX ix_events_boss_id ON events (boss_id);

CREATE INDEX ix_events_channel_id ON events (channel_id);

CREATE UNIQUE INDEX ix_events_event_hash ON events (event_hash);

CREATE INDEX ix_events_item_id ON events (item_id);

CREATE INDEX ix_events_killer_player_id_action_type_id ON events (killer_player_id, action_type_id);

CREATE INDEX ix_events_occurred_at ON events (occurred_at);

CREATE INDEX ix_events_player_id_action_type_id ON events (player_id, action_type_id);

CREATE INDEX ix_events_quest_id ON events (quest_id);

CREATE INDEX ix_events_victim_player_id_action_type_id ON events (victim_player_id, action_type_id);

CREATE INDEX ix_events_zone_id ON events (zone_id);

CREATE UNIQUE INDEX ix_items_name ON items (name);

CREATE INDEX ix_players_last_known_zone_id ON players (last_known_zone_id);

CREATE INDEX ix_players_name ON players (name);

CREATE UNIQUE INDEX ix_zones_name ON zones (name);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260215071652_InitialCreate', '8.0.24');

COMMIT;

